### ISSUE TITLE
Divider的颜色可以改成默认的吗

### ISSUE THREAD

**Issue by lhlyu** [flutter-library-provider/FlutterUpgrader#1]
改成这样就好：`const Divider(height: 1)`，它的颜色默认继承：
```
dividerTheme: const DividerThemeData(
  color: Colors.black12,
),
```

现在代码是默认写死的：[https://github.com/flutter-library-provider/FlutterUpgrader/blob/main/lib/flutter_upgrader_view.dart](https://github.com/flutter-library-provider/FlutterUpgrader/blob/main/lib/flutter_upgrader_view.dart)

**Comment by linpengteng** [comment]
OK，这个可以有

**Comment by linpengteng** [comment]
已支持, 如下两种皆可

No1.
```dart
  DividerTheme(
     data: const DividerThemeData(color: Colors.red), // support
     child: ...,
  ),
```

<br/>

No2.
```dart
   AppUpgradeManager.upgrade(
        context,
        iosAppId: '',
        appUpgradeInfo,
        dividerTheme: const DividerThemeData(color: Colors.blue), // support
  );
```

<br/>

详见:  https://github.com/flutter-library-provider/FlutterUpgrader/blob/main/example/lib/main.dart

**Comment by linpengteng** [comment]
如果没问题了，到时候关闭下 issues
