### ISSUE TITLE
物理按键

### ISSUE THREAD

**Issue by yangdehui** [flutter-library-provider/FlutterUpgrader#4]
安卓机物理返回，强制更新可以绕过去

**Comment by linpengteng** [comment]
感谢反馈，明天我试试

**Comment by linpengteng** [comment]
确实，强制更新本是推入一个新的 Route，并在 UI 上控制了 back 的相关操作。安卓机物理的返回绕过了  UI 的控制，暂时没有解决方案

**Comment by linpengteng** [comment]
需要在 GetMaterialApp 配置 backButtonDispatcher，实现物理键返回时进行拦截处理
